### ISSUE TITLE
remove: Nick Jr. Too

### ISSUE THREAD

**Issue by mavijavi5124** [frostiptv/frostiptv.github.io#5]
### broken stream

http://84.203.199.198:9981/stream/service/f9551ab09a03891df8dba84a95277fab

### what happened to the stream?

not loading

**Comment by shiawasevip** [comment]
yeah /service links are usually unstable but they work

**Comment by mavijavi5124** [comment]
> yeah /service links are usually unstable but they work

How many hours do they stay alive tho?

**Comment by shiawasevip** [comment]
not sure but if i had to guess probably around 3?

**Comment by shiawasevip** [comment]
and then go down for like an hour
