### ISSUE TITLE
remove: Canadian Channels broken 

### ISSUE THREAD

**Issue by mavijavi5124** [frostiptv/frostiptv.github.io#8]
### broken stream

Multiple 

### what happened to the stream?

other

### notes

Canadian Channels are unstable and Boomerang Ca showed a message

**Comment by shiawasevip** [comment]
the person who runned those streams locked the source, probably for maintenance, ill wait 2 days and if nothing happens theyll be removed

**Comment by mavijavi5124** [comment]
> the person who runned those streams locked the source, probably for maintenance, ill wait 2 days and if nothing happens theyll be removed

Seems to be up again

**Comment by mavijavi5124** [comment]
its super unstable tho

**Comment by shiawasevip** [comment]
yeah i replaced the links a few hours ago
